export enum ErrorCodesEnum {
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    PASSWORD_INCORRECT = 'PASSWORD_INCORRECT',
    EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
    USER_INACTIVE = 'USER_INACTIVE',
    ACCESS_DENIED = 'ACCESS_DENIED',
}
